name: Netlify Deploy

on:
  issues:
    types: [opened, edited, closed, deleted, reopened, labeled, unlabeled]

  issue_comment:
    types: [created, edited, deleted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Netlify Hook
      run: curl -X POST ${{ secrets.netlify_rebuild }}
